### ISSUE TITLE
gather-external-docs fails due to moved OH2 addons feature file

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-docs#914]
In https://github.com/openhab/openhab2-addons/pull/5018 the openhab2-addons feature file was moved:

`features/openhab-addons/src/main/feature/feature.xml`
→ 
`features/karaf/openhab-addons/src/main/feature/feature.xml`

---

As a result the [gather-external-docs](https://ci.openhab.org/view/Documentation/job/gather-external-docs/194/console) Jenkins job now fails with:

`[ERROR] Failed to execute goal org.codehaus.groovy.maven:gmaven-plugin:1.0:execute (process-addon-files) on project docs: java.io.FileNotFoundException: /var/jenkins_home/workspace/gather-external-docs/.external-resources/openhab2-addons/features/openhab-addons/src/main/feature/feature.xml (No such file or directory) -> [Help 1]`

This also causes https://github.com/openhab/openhab-docs/issues/908.

Can you have a look at this @openhab/documentation-maintainers ?

**Comment by openhab-5iver** [comment]
This was corrected in #909, but it has not yet been merged.

**Comment by Confectrician** [comment]
Sorry for the delay.
I have merged the PR now and started a build to see if its working again.

**Comment by Confectrician** [comment]
Obviously this didn't solve it, sicne we cant adapt maven stuff with in markdown files.^^

We need to adapt the final branch and the pom.xml probably.
I will have to check that first.

**Comment by Confectrician** [comment]
![image](https://user-images.githubusercontent.com/7161177/54151640-967c5280-443b-11e9-98ac-dc5251d493ff.png)


Looks good on my machine. PR incoming.

**Comment by wborn** [comment]
Thanks for fixing it @Confectrician! I see the build succeeds again so I'll close this issue. :smiley:

**Comment by Confectrician** [comment]
Perfect alltough the issue should have been closed automatically.

I am pretty sure that I used the correct keyword.

**Comment by wborn** [comment]
Yes I was also surprised about that and couldn't find any explanation for it.
